version: "3"
services:
  nginx:
    ports:
      - 80:80
  node-app:
    build:
      context: . # location of Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=darula
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev

  mongo-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=darula
      - MONGO_INITDB_ROOT_PASSWORD=password
