version: "3"
services:
  nginx:
    ports:
      - 80:80
  node-app:
    build:
      context: . # location of Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start
