version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    environment:
      - PORT=4000
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=darula
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/ # create a volume name mongo-db and map it to /data/ within container

  redis:
    image: redis

volumes:
  mongo-db:
